### ISSUE TITLE
Actor, Director, Producer Information

### ISSUE THREAD

**Issue by bonelifer** [SchedulesDirect/mfdb-json#6]
mfdb-json doesn't seem to be producing the actor, director, producer information that tv_grab_na_sd does when filling mythtv's database. Personally I find being able to click on these in mythweb and find more shows/movies by the actor/director/producer invaluable for scheduling purposes.

**Comment by rkulagowski** [comment]
I have rewritten the code that was doing the person updates into the MythTV database so this should finally be fixed.

**Comment by bonelifer** [comment]
Still seems to not always populate Mythtv Category "Children" fully. Some none at all. Others Director/Producer are filled in, but none of the voice actors.

**Comment by rkulagowski** [comment]
Can you give me a specific example? I have to mash 300+ "roles" into the 5 or 6 that MythTV actually knows about (it uses an ENUM, so it can only be those 5 or 6) and I may have missed an entry.

**Comment by bonelifer** [comment]
Madagascar: Escape 2 Africa
http://william-mythtv/mythweb/tv/detail/16158/1420923600 
Program ID: MV002145230000
```
Directed by: 	Tom McGrath, Eric Darnell
Produced by: 	Mireille Soria, Mark Swift
Written by: 	Etan Cohen, Tom McGrath, Eric Darnell
```


This next one is totally deviod of anything actor/procucer/director related:

Steven Universe:Warp Tour 
http://william-mythtv/mythweb/tv/detail/16136/1421365500 
Program ID: EP016164320063

**Comment by rkulagowski** [comment]
OK, if you git pull you should be OK now; I'm mapping "Voice" in the raw data to "Actor".

For the Steven Universe example, the JSON is:

"cast": [
        {
            "personId": "628431",
            "nameId": "650233",
            "name": "Zach Callison",
            "role": "Voice",
            "billingOrder": "01"
        },
        {
            "personId": "519076",
            "nameId": "536351",
            "name": "Estelle",
            "role": "Voice",
            "billingOrder": "02"
        },
        {
            "personId": "394506",
            "nameId": "792338",
            "name": "Deedee Magno Hall",
            "role": "Voice",
            "billingOrder": "03"
        },
        {
            "personId": "635578",
            "nameId": "658722",
            "name": "Michaela Dietz",
            "role": "Voice",
            "billingOrder": "04"
        }
    ],

So since everything was "Voice" it was all blank. That's fixed now.

**Comment by bonelifer** [comment]
Thanks. Looks good.

**Comment by bonelifer** [comment]
Is this functionality still part of any branch? Just noticed it stopped adding the info. Not sure when this started.

**Comment by rkulagowski** [comment]
It's still in the raw data; I was working on getting API 20141201 out the
door, so I will need to take a look and see.

Which version of the grabber are you using?

**Comment by bonelifer** [comment]
command: git show -s --pretty=%d HEAD
 (HEAD, origin/API-20140530-test, API-20140530-test)

**Comment by bonelifer** [comment]
Ok, I can only guess maybe the movies/shows I looked at earlier, were far enough out toward the end of the 13 days that they were missing "some" information. Either that or a weird bug. Because they are now filled again.

**Comment by rkulagowski** [comment]
Have you had any other issues or can I close this ticket?

**Comment by bonelifer** [comment]
Go ahead and close.
